---
- name: Clean APT Cache (1/3)
  ansible.builtin.apt:
    clean: true

- name: Find APT cache and DHCP files
  ansible.builtin.find:
    paths:
      - /var/cache/apt
      - /var/lib/dhcp
    hidden: yes
    file_type: any
  register: apt_cache_files

- name: Remove APT cache files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ apt_cache_files.files }}"
  when: apt_cache_files.files | length > 0
  changed_when: true

- name: Find APT library files
  ansible.builtin.find:
    paths: /var/lib/apt
    hidden: yes
    file_type: any
    excludes:
      - lock
      - lists
    patterns: "*"
  register: apt_lib_files

- name: Remove APT library files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ apt_lib_files.files }}"
  when: apt_lib_files.files | length > 0
  changed_when: true

- name: Remove bash_history file
  ansible.builtin.file:
    path: /root/.bash_history
    state: absent

- name: Disabled cloud-init
  ansible.builtin.file:
    path: /etc/cloud/cloud-init.disabled
    state: absent
